//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 10:20:28 PM CEST 
//


package org.example.instrumenti_placanja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NalogZaPrenos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NalogZaPrenos">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/instrumenti_placanja}SredstvoPlacanja">
 *       &lt;sequence>
 *         &lt;element name="racun_duznika" type="{http://www.example.org/instrumenti_placanja}BrojRacuna"/>
 *         &lt;element name="model_zaduzenja" type="{http://www.example.org/instrumenti_placanja}Model" minOccurs="0"/>
 *         &lt;element name="poziv_na_broj_zaduzenja" type="{http://www.example.org/instrumenti_placanja}PozivNaBroj" minOccurs="0"/>
 *         &lt;element name="racun_povjerioca" type="{http://www.example.org/instrumenti_placanja}BrojRacuna"/>
 *         &lt;element name="model_odobrenja" type="{http://www.example.org/instrumenti_placanja}Model" minOccurs="0"/>
 *         &lt;element name="poziv_na_broj_odobrenja" type="{http://www.example.org/instrumenti_placanja}PozivNaBroj" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NalogZaPrenos", propOrder = {
    "racunDuznika",
    "modelZaduzenja",
    "pozivNaBrojZaduzenja",
    "racunPovjerioca",
    "modelOdobrenja",
    "pozivNaBrojOdobrenja"
})
public class NalogZaPrenos
    extends SredstvoPlacanja
{

    @XmlElement(name = "racun_duznika", required = true)
    protected String racunDuznika;
    @XmlElement(name = "model_zaduzenja")
    protected Short modelZaduzenja;
    @XmlElement(name = "poziv_na_broj_zaduzenja")
    protected String pozivNaBrojZaduzenja;
    @XmlElement(name = "racun_povjerioca", required = true)
    protected String racunPovjerioca;
    @XmlElement(name = "model_odobrenja")
    protected Short modelOdobrenja;
    @XmlElement(name = "poziv_na_broj_odobrenja")
    protected String pozivNaBrojOdobrenja;

    /**
     * Gets the value of the racunDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRacunDuznika() {
        return racunDuznika;
    }

    /**
     * Sets the value of the racunDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRacunDuznika(String value) {
        this.racunDuznika = value;
    }

    /**
     * Gets the value of the modelZaduzenja property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getModelZaduzenja() {
        return modelZaduzenja;
    }

    /**
     * Sets the value of the modelZaduzenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setModelZaduzenja(Short value) {
        this.modelZaduzenja = value;
    }

    /**
     * Gets the value of the pozivNaBrojZaduzenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPozivNaBrojZaduzenja() {
        return pozivNaBrojZaduzenja;
    }

    /**
     * Sets the value of the pozivNaBrojZaduzenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPozivNaBrojZaduzenja(String value) {
        this.pozivNaBrojZaduzenja = value;
    }

    /**
     * Gets the value of the racunPovjerioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRacunPovjerioca() {
        return racunPovjerioca;
    }

    /**
     * Sets the value of the racunPovjerioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRacunPovjerioca(String value) {
        this.racunPovjerioca = value;
    }

    /**
     * Gets the value of the modelOdobrenja property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getModelOdobrenja() {
        return modelOdobrenja;
    }

    /**
     * Sets the value of the modelOdobrenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setModelOdobrenja(Short value) {
        this.modelOdobrenja = value;
    }

    /**
     * Gets the value of the pozivNaBrojOdobrenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPozivNaBrojOdobrenja() {
        return pozivNaBrojOdobrenja;
    }

    /**
     * Sets the value of the pozivNaBrojOdobrenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPozivNaBrojOdobrenja(String value) {
        this.pozivNaBrojOdobrenja = value;
    }

}
