//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 10:20:28 PM CEST 
//


package org.example.instrumenti_placanja;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.instrumenti_placanja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.instrumenti_placanja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstrumentiPlacanja }
     * 
     */
    public InstrumentiPlacanja createInstrumentiPlacanja() {
        return new InstrumentiPlacanja();
    }

    /**
     * Create an instance of {@link NalogZaPrenos }
     * 
     */
    public NalogZaPrenos createNalogZaPrenos() {
        return new NalogZaPrenos();
    }

    /**
     * Create an instance of {@link NalogZaIsplatu }
     * 
     */
    public NalogZaIsplatu createNalogZaIsplatu() {
        return new NalogZaIsplatu();
    }

    /**
     * Create an instance of {@link NalogZaUplatu }
     * 
     */
    public NalogZaUplatu createNalogZaUplatu() {
        return new NalogZaUplatu();
    }

}
