//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 10:20:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/instrumenti_placanja", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.instrumenti_placanja;
