//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 10:20:28 PM CEST 
//


package org.example.instrumenti_placanja;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SredstvoPlacanja complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SredstvoPlacanja">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naziv_duznika" type="{http://www.example.org/instrumenti_placanja}NazivSvrha"/>
 *         &lt;element name="naziv_povjerioca" type="{http://www.example.org/instrumenti_placanja}NazivSvrha"/>
 *         &lt;element name="svrha_placanja" type="{http://www.example.org/instrumenti_placanja}NazivSvrha"/>
 *         &lt;element name="datum_prijema" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datum_izvrsenja" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sifra_placanja" type="{http://www.example.org/instrumenti_placanja}SifraPlacanja"/>
 *         &lt;element name="valuta" type="{http://www.example.org/instrumenti_placanja}Valuta"/>
 *         &lt;element name="iznos" type="{http://www.example.org/instrumenti_placanja}Iznos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SredstvoPlacanja", propOrder = {
    "nazivDuznika",
    "nazivPovjerioca",
    "svrhaPlacanja",
    "datumPrijema",
    "datumIzvrsenja",
    "sifraPlacanja",
    "valuta",
    "iznos"
})
@XmlSeeAlso({
    NalogZaPrenos.class,
    NalogZaIsplatu.class,
    NalogZaUplatu.class
})
public abstract class SredstvoPlacanja {

    @XmlElement(name = "naziv_duznika", required = true)
    protected String nazivDuznika;
    @XmlElement(name = "naziv_povjerioca", required = true)
    protected String nazivPovjerioca;
    @XmlElement(name = "svrha_placanja", required = true)
    protected String svrhaPlacanja;
    @XmlElement(name = "datum_prijema", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPrijema;
    @XmlElement(name = "datum_izvrsenja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzvrsenja;
    @XmlElement(name = "sifra_placanja")
    protected short sifraPlacanja;
    @XmlElement(required = true)
    protected String valuta;
    @XmlElement(required = true)
    protected BigDecimal iznos;

    /**
     * Gets the value of the nazivDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivDuznika() {
        return nazivDuznika;
    }

    /**
     * Sets the value of the nazivDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivDuznika(String value) {
        this.nazivDuznika = value;
    }

    /**
     * Gets the value of the nazivPovjerioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPovjerioca() {
        return nazivPovjerioca;
    }

    /**
     * Sets the value of the nazivPovjerioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPovjerioca(String value) {
        this.nazivPovjerioca = value;
    }

    /**
     * Gets the value of the svrhaPlacanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvrhaPlacanja() {
        return svrhaPlacanja;
    }

    /**
     * Sets the value of the svrhaPlacanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvrhaPlacanja(String value) {
        this.svrhaPlacanja = value;
    }

    /**
     * Gets the value of the datumPrijema property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPrijema() {
        return datumPrijema;
    }

    /**
     * Sets the value of the datumPrijema property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPrijema(XMLGregorianCalendar value) {
        this.datumPrijema = value;
    }

    /**
     * Gets the value of the datumIzvrsenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzvrsenja() {
        return datumIzvrsenja;
    }

    /**
     * Sets the value of the datumIzvrsenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzvrsenja(XMLGregorianCalendar value) {
        this.datumIzvrsenja = value;
    }

    /**
     * Gets the value of the sifraPlacanja property.
     * 
     */
    public short getSifraPlacanja() {
        return sifraPlacanja;
    }

    /**
     * Sets the value of the sifraPlacanja property.
     * 
     */
    public void setSifraPlacanja(short value) {
        this.sifraPlacanja = value;
    }

    /**
     * Gets the value of the valuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuta() {
        return valuta;
    }

    /**
     * Sets the value of the valuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuta(String value) {
        this.valuta = value;
    }

    /**
     * Gets the value of the iznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznos() {
        return iznos;
    }

    /**
     * Sets the value of the iznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznos(BigDecimal value) {
        this.iznos = value;
    }

}
